//
//  TwitterUser+CoreDataProperties.swift
//  TwitterDemo
//
//  Created by  on 30/06/17.
//  Copyright © 2017 ., Pune. All rights reserved.
//

/*--- Extension for coredata attributes 'Autogenerated'---*/

import Foundation
import CoreData

extension TwitterUser {

    @nonobjc public class func fetchRequest() -> NSFetchRequest<TwitterUser> {
        return NSFetchRequest<TwitterUser>(entityName: "TwitterUser")
    }

    @NSManaged public var name: String?
    @NSManaged public var id: String?
    @NSManaged public var created_at: NSDate?
    @NSManaged public var screen_name: String?
    @NSManaged public var text: String?

}
